apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: runexample-
spec:
  taskref:
    name: example
  params:
    - name: string_params
      value: "runtask string parameter echo"

    - name: array_params
      value:
        - "array1"
        - "array2"
        - "array3"
